import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
=======
import { Manrope, Noto_Sans_Arabic, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "@/i18n/provider";
import { ToastStack } from "@/components/toast-stack";
import { ChatWidget } from "@/components/chat-widget";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const arabic = Noto_Sans_Arabic({
  variable: "--font-arabic",
  subsets: ["arabic"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
>>>>>>> 860ec09 (Initial commit - Crop Advisor SaaS)
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Crop Advisor SaaS",
  description: "AI-powered agricultural telemetry and recommendations platform",
>>>>>>> 860ec09 (Initial commit - Crop Advisor SaaS)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
<<<<<<< HEAD
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
      className={`${manrope.variable} ${arabic.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <I18nProvider>
          {children}
          <ToastStack />
          <ChatWidget />
        </I18nProvider>
      </body>
>>>>>>> 860ec09 (Initial commit - Crop Advisor SaaS)
    </html>
  );
}
