// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use direct connection for Prisma schema operations; fallback keeps local docker setup simple.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
