/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_904585_5[] = { "anomaly" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_904585_31_axes[] = { 0, 1, 2, 3, 4 };
const uint32_t ei_dsp_config_904585_31_axes_size = 5;
ei_dsp_config_flatten_t ei_dsp_config_904585_31 = {
    31, // uint32_t blockId
    1, // int implementationVersion
    5, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const uint8_t ei_dsp_blocks_904585_5_size = 1;
ei_model_dsp_t ei_dsp_blocks_904585_5[ei_dsp_blocks_904585_5_size] = {
    { // DSP block 31
        31,
        35, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_904585_31, // pointer to config struct
        ei_dsp_config_904585_31_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_904585_31_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        nullptr, // data normalization config
    }
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_904585_32 = {
    .implementation_version = 1,
    .block_id = 32,
    .anom_axis = ei_classifier_anom_axes_904585_32,
    .anom_axes_size = 10,
    .anom_clusters = ei_classifier_anom_clusters_904585_32,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_904585_32,
    .anom_mean = ei_classifier_anom_mean_904585_32,
};

const uint8_t ei_learning_blocks_904585_5_size = 1;
const uint32_t ei_learning_block_904585_32_inputs[1] = { 31 };
const uint8_t ei_learning_block_904585_32_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_904585_5[ei_learning_blocks_904585_5_size] = {
    {
        32,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_904585_32,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_904585_32_inputs,
        ei_learning_block_904585_32_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_904585_5_size = 0;
const ei_postprocessing_block_t *ei_postprocessing_blocks_904585_5 = nullptr;

const uint8_t freeform_outputs_904585_5_size = 0;

uint32_t *freeform_outputs_904585_5 = nullptr;

const ei_impulse_t impulse_904585_5 = {
    .project_id = 904585,
    .project_owner = "mohamed_said",
    .project_name = "mohamed_said-project-1",
    .impulse_id = 5,
    .impulse_name = "Impulse #5",
    .deploy_version = 12,

    .nn_input_frame_size = 35,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 5,
    .dsp_input_frame_size = 1 * 5,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1000,
    .frequency = 1,

    .dsp_blocks_size = ei_dsp_blocks_904585_5_size,
    .dsp_blocks = ei_dsp_blocks_904585_5,

    .learning_blocks_size = ei_learning_blocks_904585_5_size,
    .learning_blocks = ei_learning_blocks_904585_5,

    .postprocessing_blocks_size = ei_postprocessing_blocks_904585_5_size,
    .postprocessing_blocks = ei_postprocessing_blocks_904585_5,

    .output_tensors_size = 0,

    .inferencing_engine = EI_CLASSIFIER_NONE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temperature + humidity + soil_moisture + lux + flow_rate",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories_904585_5,
    .results_type = EI_CLASSIFIER_TYPE_NONE,
    .freeform_outputs_size = freeform_outputs_904585_5_size,
    .freeform_outputs = freeform_outputs_904585_5
};

ei_impulse_handle_t impulse_handle_904585_5 = ei_impulse_handle_t( &impulse_904585_5 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_904585_5;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_904585_5;
const auto ei_dsp_blocks_size = ei_dsp_blocks_904585_5_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_904585_5;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
